package com.blogweb.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
//		arp.addMapping("lesson_eval", "", LessonEval.class);
		arp.addMapping("lessons", "id", Lessons.class);
		arp.addMapping("lessons_plan", "id", LessonsPlan.class);
//		arp.addMapping("lessons_type", "", LessonsType.class);
		arp.addMapping("user_base", "id", UserBase.class);
	}
}

