package com.blogweb.model;

import com.blogweb.model.base.BaseUserBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserBase extends BaseUserBase<UserBase> {
	public static final UserBase dao = new UserBase();
}
