package com.blogweb.model;

import com.blogweb.model.base.BaseZnComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnComment extends BaseZnComment<ZnComment> {
	public static final ZnComment dao = new ZnComment();
}
