package com.blogweb.model;

import com.blogweb.model.base.BaseZnLessons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnLessons extends BaseZnLessons<ZnLessons> {
	public static final ZnLessons dao = new ZnLessons();
}
