package com.blogweb.model;

import com.blogweb.model.base.BaseZnLessonsPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZnLessonsPlan extends BaseZnLessonsPlan<ZnLessonsPlan> {
	public static final ZnLessonsPlan dao = new ZnLessonsPlan();
}
